local DataStorage = require("datastorage")
local UIManager = require("ui/uimanager")
local InfoMessage = require("ui/widget/infomessage")
local _ = require("appstore_gettext")
local http = require("socket.http")
local ltn12 = require("ltn12")
local util = require("util")
local logger = require("logger")
local lfs = require("libs/libkoreader-lfs")

local ok_cfg, AppStoreConfig = pcall(require, "appstore_configuration")
if not ok_cfg then
    AppStoreConfig = {}
end

local RepoContent = {}

local DEFAULT_PROXY = "https://gh-proxy.com"

local function proxyUrl(raw_url)
    local proxy = AppStoreConfig.proxy_url
    if proxy == nil then
        proxy = DEFAULT_PROXY
    end
    if proxy and proxy ~= "" then
        return proxy .. "/" .. raw_url
    end
    return raw_url
end

local function getCacheDir()
    local dir = DataStorage:getDataDir() .. "/cache/appstore/readme"
    local ok, err = util.makePath(dir)
    if not ok then
        logger.warn("AppStore README cache dir failure", err)
    end
    return dir
end

local function buildRawUrl(owner, repo)
    return proxyUrl(string.format("https://raw.githubusercontent.com/%s/%s/HEAD/README.md", owner, repo))
end

local function download(url)
    local response = {}
    local _, code = http.request{
        url = url,
        sink = ltn12.sink.table(response),
        headers = {
            ["Accept"] = "text/plain",
            ["User-Agent"] = "KOReader-AppStore",
        },
    }
    return tonumber(code), table.concat(response)
end

function RepoContent.fetchReadme(owner, repo)
    if not owner or not repo then
        return false, "missing owner/repo"
    end
    local url = buildRawUrl(owner, repo)
    local code, body = download(url)
    if code ~= 200 then
        return false, string.format("HTTP %s", tostring(code))
    end
    if not body or body == "" then
        return false, "empty body"
    end
    body = body:gsub("<img[^>]->", "")
    return true, body
end

-- Remove every cached README markdown file generated by RepoContent.fetchReadme.
-- Returns a table with `removed` count and `errors` list (failed file paths).
function RepoContent.clearReadmeCache()
    local dir = DataStorage:getDataDir() .. "/cache/appstore/readme"
    local removed = 0
    local errors = {}
    if lfs.attributes(dir, "mode") ~= "directory" then
        return { removed = 0, errors = errors }
    end
    for entry in lfs.dir(dir) do
        if entry ~= "." and entry ~= ".." then
            local full_path = dir .. "/" .. entry
            local mode = lfs.attributes(full_path, "mode")
            if mode == "file" then
                local ok = os.remove(full_path)
                if ok then
                    removed = removed + 1
                else
                    table.insert(errors, full_path)
                end
            end
        end
    end
    return { removed = removed, errors = errors }
end

return RepoContent

